# 0. Import libraries/packages

In [1]:
import pandas as pd
import os
from datetime import date, timedelta
from pathlib import Path

# 1. Data Exploration

## 1.0 Initial lookup

In [2]:
data_path = '../data/historical_data/flights.csv'

In [3]:
data = pd.read_csv(data_path, low_memory=False)

In [4]:
data.columns

Index(['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'FLIGHT_NUMBER',
       'TAIL_NUMBER', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT',
       'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'TAXI_OUT',
       'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'WHEELS_ON', 'TAXI_IN', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME',
       'ARRIVAL_DELAY', 'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON',
       'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY',
       'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY'],
      dtype='str')

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 31 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   MONTH                int64
 2   DAY                  int64
 3   DAY_OF_WEEK          int64
 4   AIRLINE              str
 5   FLIGHT_NUMBER        int64
 6   TAIL_NUMBER          str
 7   ORIGIN_AIRPORT       str
 8   DESTINATION_AIRPORT  str
 9   SCHEDULED_DEPARTURE  int64
 10  DEPARTURE_TIME       float64
 11  DEPARTURE_DELAY      float64
 12  TAXI_OUT             float64
 13  WHEELS_OFF           float64
 14  SCHEDULED_TIME       float64
 15  ELAPSED_TIME         float64
 16  AIR_TIME             float64
 17  DISTANCE             int64
 18  WHEELS_ON            float64
 19  TAXI_IN              float64
 20  SCHEDULED_ARRIVAL    int64
 21  ARRIVAL_TIME         float64
 22  ARRIVAL_DELAY        float64
 23  DIVERTED             int64
 24  CANCELLED            int64
 25  CANCELLATION_REASON  str
 26  AIR_SYSTEM_DELAY     float64
 27  SECURITY_DELAY       float64
 28  AIRLINE_DELAY        float64
 29  LATE_AIRCRAFT_DELAY  float64
 30  WEATHER_DELAY        float64
dtypes: float64(16), int64(10), str(5)
memory usage: 1.3 GB

In [6]:
data.shape

(5819079, 31)

In [7]:
data.count()

YEAR                   5819079
MONTH                  5819079
DAY                    5819079
DAY_OF_WEEK            5819079
AIRLINE                5819079
FLIGHT_NUMBER          5819079
TAIL_NUMBER            5804358
ORIGIN_AIRPORT         5819079
DESTINATION_AIRPORT    5819079
SCHEDULED_DEPARTURE    5819079
DEPARTURE_TIME         5732926
DEPARTURE_DELAY        5732926
TAXI_OUT               5730032
WHEELS_OFF             5730032
SCHEDULED_TIME         5819073
ELAPSED_TIME           5714008
AIR_TIME               5714008
DISTANCE               5819079
WHEELS_ON              5726566
TAXI_IN                5726566
SCHEDULED_ARRIVAL      5819079
ARRIVAL_TIME           5726566
ARRIVAL_DELAY          5714008
DIVERTED               5819079
CANCELLED              5819079
CANCELLATION_REASON      89884
AIR_SYSTEM_DELAY       1063439
SECURITY_DELAY         1063439
AIRLINE_DELAY          1063439
LATE_AIRCRAFT_DELAY    1063439
WEATHER_DELAY          1063439
dtype: int64

In [8]:
data.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

## 1.1 Data Load

### 1.1.1 Data types mapping

In [9]:
dtype_mapping = {
    'YEAR': 'Int16',
    'MONTH': 'Int8',
    'DAY': 'Int8',
    'DAY_OF_WEEK': 'Int8',

    'AIRLINE': 'string',
    'FLIGHT_NUMBER': 'Int32',
    'TAIL_NUMBER': 'string',

    'ORIGIN_AIRPORT': 'string',
    'DESTINATION_AIRPORT': 'string',

    'SCHEDULED_DEPARTURE': 'string',
    'DEPARTURE_TIME': 'string',
    'WHEELS_OFF': 'string',
    'TAXI_OUT': 'Int32',

    'SCHEDULED_TIME': 'string',
    'ELAPSED_TIME': 'Int32',
    'AIR_TIME': 'Int32',

    'SCHEDULED_ARRIVAL': 'string',
    'ARRIVAL_TIME': 'string',
    'WHEELS_ON': 'string',
    'TAXI_IN': 'Int32',

    'DEPARTURE_DELAY': 'Float32',
    'ARRIVAL_DELAY': 'Float32',
    'DISTANCE': 'Int32',

    'DIVERTED': 'Int8',
    'CANCELLED': 'Int8',
    'CANCELLATION_REASON': 'string',

    'AIR_SYSTEM_DELAY': 'Float32',
    'SECURITY_DELAY': 'Float32',
    'AIRLINE_DELAY': 'Float32',
    'LATE_AIRCRAFT_DELAY': 'Float32',
    'WEATHER_DELAY': 'Float32'
}

### 1.1.2 Data loading to pandas

In [10]:
# data = pd.read_csv('flights.csv', low_memory=False)
df = pd.read_csv(data_path, dtype = dtype_mapping, low_memory=False)

In [11]:
df.columns

Index(['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'FLIGHT_NUMBER',
       'TAIL_NUMBER', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT',
       'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'TAXI_OUT',
       'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'WHEELS_ON', 'TAXI_IN', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME',
       'ARRIVAL_DELAY', 'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON',
       'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY',
       'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY'],
      dtype='str')

### 1.1.3 Data info

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 31 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 Int16
 1   MONTH                Int8
 2   DAY                  Int8
 3   DAY_OF_WEEK          Int8
 4   AIRLINE              string
 5   FLIGHT_NUMBER        Int32
 6   TAIL_NUMBER          string
 7   ORIGIN_AIRPORT       string
 8   DESTINATION_AIRPORT  string
 9   SCHEDULED_DEPARTURE  string
 10  DEPARTURE_TIME       string
 11  DEPARTURE_DELAY      Float32
 12  TAXI_OUT             Int32
 13  WHEELS_OFF           string
 14  SCHEDULED_TIME       string
 15  ELAPSED_TIME         Int32
 16  AIR_TIME             Int32
 17  DISTANCE             Int32
 18  WHEELS_ON            string
 19  TAXI_IN              Int32
 20  SCHEDULED_ARRIVAL    string
 21  ARRIVAL_TIME         string
 22  ARRIVAL_DELAY        Float32
 23  DIVERTED             Int8
 24  CANCELLED            Int8
 25  CANCELLATION_REASON  string
 26  AIR_SYSTEM_DELAY     Float32
 27  SECURITY_DELAY       Float32
 28  AIRLINE_DELAY        Float32
 29  LATE_AIRCRAFT_DELAY  Float32
 30  WEATHER_DELAY        Float32
dtypes: Float32(7), Int16(1), Int32(6), Int8(5), string(12)
memory usage: 965.6 MB

In [13]:
df.count()

YEAR                   5819079
MONTH                  5819079
DAY                    5819079
DAY_OF_WEEK            5819079
AIRLINE                5819079
FLIGHT_NUMBER          5819079
TAIL_NUMBER            5804358
ORIGIN_AIRPORT         5819079
DESTINATION_AIRPORT    5819079
SCHEDULED_DEPARTURE    5819079
DEPARTURE_TIME         5732926
DEPARTURE_DELAY        5732926
TAXI_OUT               5730032
WHEELS_OFF             5730032
SCHEDULED_TIME         5819073
ELAPSED_TIME           5714008
AIR_TIME               5714008
DISTANCE               5819079
WHEELS_ON              5726566
TAXI_IN                5726566
SCHEDULED_ARRIVAL      5819079
ARRIVAL_TIME           5726566
ARRIVAL_DELAY          5714008
DIVERTED               5819079
CANCELLED              5819079
CANCELLATION_REASON      89884
AIR_SYSTEM_DELAY       1063439
SECURITY_DELAY         1063439
AIRLINE_DELAY          1063439
LATE_AIRCRAFT_DELAY    1063439
WEATHER_DELAY          1063439
dtype: int64

In [14]:
df.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,0005,...,0408,-22.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,0010,...,0741,-9.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,2015,1,1,4,US,840,N171US,SFO,CLT,0020,...,0811,5.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,0020,...,0756,-9.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,0025,...,0259,-21.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [15]:
COLUMN_MAP = {
    "YEAR": "year",
    "MONTH": "month",
    "DAY": "day",
    "DAY_OF_WEEK": "day_of_week",
    "AIRLINE": "airline",
    "FLIGHT_NUMBER": "flight_number",
    "TAIL_NUMBER": "tail_number",
    "ORIGIN_AIRPORT": "origin_airport",
    "DESTINATION_AIRPORT": "destination_airport",
    "SCHEDULED_DEPARTURE": "scheduled_departure",
    "DEPARTURE_TIME": "departure_time",
    "DEPARTURE_DELAY": "departure_delay",
    "TAXI_OUT": "taxi_out",
    "WHEELS_OFF": "wheels_off",
    "SCHEDULED_TIME": "scheduled_time",
    "ELAPSED_TIME": "elapsed_time",
    "AIR_TIME": "air_time",
    "DISTANCE": "distance",
    "WHEELS_ON": "wheels_on",
    "TAXI_IN": "taxi_in",
    "SCHEDULED_ARRIVAL": "scheduled_arrival",
    "ARRIVAL_TIME": "arrival_time",
    "ARRIVAL_DELAY": "arrival_delay",
    "DIVERTED": "diverted",
    "CANCELLED": "cancelled",
    "CANCELLATION_REASON": "cancellation_reason",
    "AIR_SYSTEM_DELAY": "air_system_delay",
    "SECURITY_DELAY": "security_delay",
    "AIRLINE_DELAY": "airline_delay",
    "LATE_AIRCRAFT_DELAY": "late_aircraft_delay",
    "WEATHER_DELAY": "weather_delay",
}

In [ ]:
KEY_COLUMNS = [
    "FLIGHT_DATE",
    "AIRLINE",
    "FLIGHT_NUMBER",
    "ORIGIN_AIRPORT",
    "DESTINATION_AIRPORT",
]

In [17]:
required = list(COLUMN_MAP.keys())
missing = sorted(set(required) - set(df.columns))

In [18]:
df.columns

Index(['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'FLIGHT_NUMBER',
       'TAIL_NUMBER', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT',
       'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'TAXI_OUT',
       'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'WHEELS_ON', 'TAXI_IN', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME',
       'ARRIVAL_DELAY', 'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON',
       'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY',
       'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY'],
      dtype='str')

In [19]:
df['AIRLINE'].isna().any()

np.False_

In [20]:
df.duplicated(KEY_COLUMNS).sum()

np.int64(5563805)

In [23]:
df[df.duplicated(KEY_COLUMNS)]

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,FLIGHT_DATE
13951,2015,1,2,5,AS,98,N764AS,ANC,SEA,0005,...,-27.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2015-01-02
13953,2015,1,2,5,AA,2336,N3HPAA,LAX,PBI,0010,...,8.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2015-01-02
13955,2015,1,2,5,DL,1745,N319US,SMF,MSP,0015,...,-2.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2015-01-02
13957,2015,1,2,5,US,840,N172US,SFO,CLT,0020,...,12.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2015-01-02
13958,2015,1,2,5,AA,258,N3CFAA,LAX,MIA,0020,...,9.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2015-01-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5819074,2015,12,31,4,B6,688,N657JB,LAX,BOS,2359,...,-26.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2015-12-31
5819075,2015,12,31,4,B6,745,N828JB,JFK,PSE,2359,...,-16.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2015-12-31
5819076,2015,12,31,4,B6,1503,N913JB,JFK,SJU,2359,...,-8.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2015-12-31
5819077,2015,12,31,4,B6,333,N527JB,MCO,SJU,2359,...,-10.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2015-12-31
5819078,2015,12,31,4,B6,839,N534JB,JFK,BQN,2359,...,2.0,0,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2015-12-31

In [21]:
df["FLIGHT_DATE"] = pd.to_datetime(
        {"year": df["YEAR"], "month": df["MONTH"], "day": df["DAY"]},
        errors="coerce")